"""remove description

Revision ID: 5c6351216807
Revises: 3bf2ccf6e9b9
Create Date: 2026-08-23 11:24:18.826080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6351216807'
down_revision: Union[str, Sequence[str], None] = '3bf2ccf6e9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
